### PR TITLE
optimize window drag

### PR DESCRIPTION
**Pull request by fenix-hub**
Hi all! I've just bought Mad Productivity on itch.io, and I really like this so far.
I've noticed that dragging the window is extremely slow and on Windows the lag is pretty bad.
Here's a quick fix to make it smooth. Handling `OS` operations directly to the window is pretty resource-intensive in Godot as I've already experienced with some UI customization projects.
[Here's how I'm handling it in one app of mine](https://github.com/GodotNuts/FirebaseDemo-SociaDot/blob/main/main/scn/app/top_bar.gd), thanks to the team I've achieved a smooth lag-less dragging on most of desktop OS (windows, ubuntu and macOS), and I think that this implementation would be really useful for Mad Productivity UX.
I've also tried to fixed the resizing on dragging while the window is maximized, to keep the aspect ratio between the mouse position and the window's one.

Before (*release* mode, in *debug* mode the lag is even worse)
https://user-images.githubusercontent.com/45271396/141540473-3744d490-d46c-4c83-ac69-2c28c2d724b1.mp4

After (debug mode and recording the screen drops some frames, in release mode performance should be improved!)
https://user-images.githubusercontent.com/45271396/141540503-7e7cc41a-9f12-47ed-ab60-372b754cc738.mp4

Hope you find it useful.
Cheers!

### CODE REVIEW

**Review by lentsius-bark — CHANGES_REQUESTED** [review]
Compared to the previous implementation this is indeed much faster and smoother! Thanks! The only downside is that it doesn't limit the movement according to the window dimensions and can therefore allow the user to move the window slightly too far off screen.

**Comment by fenix-hub** [comment]
> 
> 
> Compared to the previous implementation this is indeed much faster and smoother! Thanks! The only downside is that it doesn't limit the movement according to the window dimensions and can therefore allow the user to move the window slightly too far off screen.

@lentsius-bark  It's a common behaviour for all windows, what the OS will automatically prevent is to move the cursor outside of the screen boundaries while dragging, so it is really hard by default to loose your window. Anyway here's a quick fix to specifically achieve what you wanted.
Notice that some calculations need to be done, since it's really hard to know what boundaries to use, since you don't know what's the min position and max size to stay in because users may have *multiple* screens with *different positions*

For example I've got two screens of different sizes, the main one is on the center (1920x1080) and the secondary screen is on my left (2400x1350), but I could have the main one on the left, and the secondary in the center, or eventually a third one.
I've added an *rough* calculation on the boundaries, and it works fine for now
 
[video](https://imgur.com/a/p3w4S9n)

**Comment by lentsius-bark** [comment]
@fenix-hub I gave this a thought and you're right, that is the normal behaviour for windows. I realized I had implemented the limit because the previous dragging hid the mouse and used event.relative to move it hence the user could move it way out.
Due to the improved window drag that shouldn't be necessary now. Hence I propose merging the previous commit without window limits, what say you? :) Again thanks for the contribution!

**Comment by fenix-hub** [comment]
@lentsius-bark Reverted to #fcdda6c :)

**Comment by lentsius-bark** [comment]
Thanks!

**Pull request merged**
